---
abstract: 'Create Sorting Networks'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
keywords:
  - sort
  - sorting-network
  - batcher
  - bitonic
  - hibbard
  - bose-nelson
  - bubble
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Networksort
provides:
  Algorithm::Networksort:
    file: lib/Algorithm/Networksort.pm
    version: 1.30
requires:
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Algorithm-Networksort.git
version: 1.30
