---
name: Algorithm-Networksort
version: 1.09
author:
  - 'John M. Gamble <jgamble@cpan.org>'
abstract: Create Sorting Networks.
license: perl
resources:
  license: ~
requires:
  perl: 5.6.0
build_requires:
  Test::Simple: 0
provides:
  Algorithm::Networksort:
    file: lib/Algorithm/Networksort.pm
    version: 1.09
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
